### ISSUE TITLE
TypeError: ("zscore() got an unexpected keyword argument 'result_type'", u'occurred at index 65286')

### ISSUE THREAD

**Issue by DavideBrex** [pinellolab/haystack_bio#10]
Hi,
I have a miniconda3 env with python 2.7 and pandas 0.21 as required.
Still, when i run **haystack_hotspots** I get the following error during the Determine High Plastic Regions (HPR) step:

```
Traceback (most recent call last):
  File "/home/davidebrex/miniconda3/envs/py27/bin/haystack_hotspots", line 10, in <module>
    sys.exit(main())
  File "/home/davidebrex/miniconda3/envs/py27/lib/python2.7/site-packages/haystack/find_hotspots.py", line 1043, in main
    output_directory)
  File "/home/davidebrex/miniconda3/envs/py27/lib/python2.7/site-packages/haystack/find_hotspots.py", line 665, in find_hpr_coordinates
    result_type ='broadcast')
  File "/home/davidebrex/miniconda3/envs/py27/lib/python2.7/site-packages/pandas/core/frame.py", line 4854, in apply
    ignore_failures=ignore_failures)
  File "/home/davidebrex/miniconda3/envs/py27/lib/python2.7/site-packages/pandas/core/frame.py", line 4950, in _apply_standard
    results[i] = func(v)
  File "/home/davidebrex/miniconda3/envs/py27/lib/python2.7/site-packages/pandas/core/frame.py", line 4831, in f
    return func(x, *args, **kwds)
TypeError: ("zscore() got an unexpected keyword argument 'result_type'", u'occurred at index 65286')

```

Any idea about what might cause this?
Thank you!

Davide

**Comment by rfarouni** [comment]
Hi,
I apologize for the delay. New Python package version updates probably broke the code. Can you please use the Docker installation method instead? https://github.com/pinellolab/haystack_bio#other-installation-options

Thanks
Rick,
