### ISSUE TITLE
haystack_download_genome error

### ISSUE THREAD

**Issue by GlenZhang-GZ** [pinellolab/haystack_bio#11]
When I use haystack_download_genome command to download the reference genome, it displayed the fowlling error:
Traceback (most recent call last):
  File "/picb/epigenome/usr/zhangge/Softwares/haystack_bio_master/haystack/download_genome.py", line 24, in <module>
    main()
  File "/picb/epigenome/usr/zhangge/Softwares/haystack_bio_master/haystack/download_genome.py", line 21, in main
    initialize_genome(args.name)
  File "/picb/epigenome/usr/zhangge/Softwares/haystack_bio_master/haystack/haystack_common.py", line 213, in initialize_genome
    from bioutilities import Genome_2bit
  File "/picb/epigenome/usr/zhangge/Softwares/haystack_bio_master/haystack/bioutilities.py", line 20, in <module>
    from bx.intervals.intersection import Intersecter, Interval
  File "/home/zhangge/miniconda3/envs/python27/lib/python2.7/site-packages/bx/intervals/__init__.py", line 7, in <module>
    from bx.intervals.intersection import *  # noqa: F40
ImportError: /home/zhangge/miniconda3/envs/python27/lib/python2.7/site-packages/bx/intervals/intersection.so: undefined symbol: PyUnicodeUCS2_FromStringAndSize

How can I solve this? Thanks!

**Comment by rfarouni** [comment]
Hi,
New Python package version updates probably broke the code. Can you please use the Docker installation method instead? https://github.com/pinellolab/haystack_bio#other-installation-options

Thanks
Rick,
