### ISSUE TITLE
Error generating normalized bigwig files

### ISSUE THREAD

**Issue by sjhosui** [pinellolab/haystack_bio#6]
I'm trying to get haystack up and running but get an out of range error generating the bigwig files. This is the output after running `haystack_run_test`.

I get a similar error when running on real data.

Thanks,
Shannan

    sambamba 0.7.0
    by Artem Tarasov and Pjotr Prins (C) 2012-2019
    LDC 1.13.0 / DMD v2.083.1 / LLVM7.0.0 / bootstrap LDC - the LLVM D compiler (0.17.6)

    sambamba-view: not enough data in stream
    Traceback (most recent call last):
    File "/Users/shosui/miniconda2/bin/haystack_hotspots", line 10, in <module>
    sys.exit(main())
    File "/Users/shosui/miniconda2/lib/python2.7/site-packages/haystack/find_hotspots.py", line 1002, in main
    args.read_ext)
    File "/Users/shosui/miniconda2/lib/python2.7/site-packages/haystack/find_hotspots.py", line 460, in to_normalized_extended_reads_tracks
    scaling_factor = get_scaling_factor(bam_filename)
    File "/Users/shosui/miniconda2/lib/python2.7/site-packages/haystack/find_hotspots.py", line 63, in get_scaling_factor
    scaling_factor = (1.0 / float(stdout.strip())) * 1000000
    ValueError: could not convert string to float: 
    Traceback (most recent call last):
    File "/Users/shosui/miniconda2/bin/haystack_pipeline", line 10, in <module>
    sys.exit(main())
    File "/Users/shosui/miniconda2/lib/python2.7/site-packages/haystack/run_pipeline.py", line 258, in main
    'Background_for_%s*.bed' % sample_name))[0]
    IndexError: list index out of range
    INFO  @ Mon, 23 Sep 2019 13:33:47:
	 Test completed successfully

**Comment by rfarouni** [comment]
The problem is probably due to the lastest numpy or pandas update. I would use the docker container or create an environment that forces these packages to have earlier versions that were released in 2017
